# Site settings
title: insp3ct0r_x's playground
email: choi.junyoung.20.04@gmail.com
description: >- 
  Everything of me
baseurl: "/" 
url: "https://juuun0.github.io"
twitter_username: insp3ct0r_x
github_username:  juuun0

# Build settings
markdown: kramdown
remote_theme: juuun0/jekyll-theme-console
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
